version: '3'
services:
  app:
    image: sandbox-laravel-testing
    working_dir: /webapp/
    build:
      context: .
      dockerfile: ./containers/app/Dockerfile
    depends_on:
      - db_testing

  db_testing:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel_testing
      MYSQL_PASSWORD: laravel_testing
      MYSQL_DATABASE: laravel_testing
