version: '3'
services:
  app:
    image: sandbox-laravel-testing
    working_dir: /webapp/
    build:
      context: .
      dockerfile: ./containers/app/Dockerfile
    volumes:
      - ./:/webapp
      - composer:/webapp/vendor
      - node_modules:/webapp/node_modules
    depends_on:
      - db
      - db_testing

  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "38194:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel_development
      MYSQL_PASSWORD: laravel_development
      MYSQL_DATABASE: laravel_development

  db_testing:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "38195:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel_testing
      MYSQL_PASSWORD: laravel_testing
      MYSQL_DATABASE: laravel_testing

volumes:
  composer:
  node_modules:
